### ISSUE TITLE
Breaks vim-mode-plus

### ISSUE THREAD

**Issue by trusktr** [hanslivingstone/keymap-control#1]
I was giving this a go after first installing vim-mode-plus. I have a few keymaps. After enabling keymap-control, I can not do anything in vim-mode-plus normal mode.

My keymaps look like this (while vim-mode-plus is enabled):

```cson
'.editor.vim-mode-plus:not(.insert-mode)':

    # vim-like tab mappings for atom-vim-like-tab plugin
    'ctrl-t': 'atom-vim-like-tab:new'
    # ': t a b n enter': 'atom-vim-like-tab:new'
    # ': t a b c enter': 'atom-vim-like-tab:close'
    'g T': 'atom-vim-like-tab:previous'
    'g t': 'atom-vim-like-tab:next'
    'space t': 'atom-vim-like-tab:list'

    # mock some common basic ex-mode commands
    # ': w enter': 'core:save'
    # ': w a enter': 'window:save-all'
    ':': 'command-palette:toggle'

    'ctrl-k': 'custom:lines-at-a-time-up'
    'ctrl-j': 'custom:lines-at-a-time-down'

# open fuzzy-find files in splits, new tab, or same tab (based on
# https://github.com/atom/fuzzy-finder/issues/81)
'.fuzzy-finder atom-text-editor[mini]':
    'ctrl-v': 'pane:split-right'
    'ctrl-s': 'pane:split-down'
    'ctrl-t': 'core:confirm'
    'enter': 'custom:replace-tab'
```

Any ideas?

**Comment by hhc8qsed** [comment]
Hey @trusktr, thanks for asking!

Hmm, haven't had any luck reproducing this against vim-mode-plus, normal mode seems to be working fine. Might be a different plugin? 

From the `keymap.cson` snippet you provided, looks like you're also using the atom-vim-like-tab plugin. If you disable that, does normal mode work? I looked through the plugin's code but nothing jumped out at me as likely to cause a problem.

Would you mind providing your OS, Atom version, installed packages, 'config' file, 'Init Script', and keymap.cson?
